export interface Wilaya {
  id: number;
  code: string;
  name: string;
  nameAr: string;
}

// Static fallback wilayas (used if API fails)
export const WILAYAS_FALLBACK: Wilaya[] = [
  { id: 1, code: '01', name: 'Adrar', nameAr: 'أدرار' },
  { id: 2, code: '02', name: 'Chlef', nameAr: 'الشلف' },
  { id: 3, code: '03', name: 'Laghouat', nameAr: 'الأغواط' },
  { id: 4, code: '04', name: 'Oum El Bouaghi', nameAr: 'أم البواقي' },
  { id: 5, code: '05', name: 'Batna', nameAr: 'باتنة' },
  { id: 6, code: '06', name: 'Béjaïa', nameAr: 'بجاية' },
  { id: 7, code: '07', name: 'Biskra', nameAr: 'بسكرة' },
  { id: 8, code: '08', name: 'Béchar', nameAr: 'بشار' },
  { id: 9, code: '09', name: 'Blida', nameAr: 'البليدة' },
  { id: 10, code: '10', name: 'Bouira', nameAr: 'البويرة' },
  { id: 11, code: '11', name: 'Tamanrasset', nameAr: 'تمنراست' },
  { id: 12, code: '12', name: 'Tébessa', nameAr: 'تبسة' },
  { id: 13, code: '13', name: 'Tlemcen', nameAr: 'تلمسان' },
  { id: 14, code: '14', name: 'Tiaret', nameAr: 'تيارت' },
  { id: 15, code: '15', name: 'Tizi Ouzou', nameAr: 'تيزي وزو' },
  { id: 16, code: '16', name: 'Alger', nameAr: 'الجزائر' },
  { id: 17, code: '17', name: 'Djelfa', nameAr: 'الجلفة' },
  { id: 18, code: '18', name: 'Jijel', nameAr: 'جيجل' },
  { id: 19, code: '19', name: 'Sétif', nameAr: 'سطيف' },
  { id: 20, code: '20', name: 'Saïda', nameAr: 'سعيدة' },
  { id: 21, code: '21', name: 'Skikda', nameAr: 'سكيكدة' },
  { id: 22, code: '22', name: 'Sidi Bel Abbès', nameAr: 'سيدي بلعباس' },
  { id: 23, code: '23', name: 'Annaba', nameAr: 'عنابة' },
  { id: 24, code: '24', name: 'Guelma', nameAr: 'قالمة' },
  { id: 25, code: '25', name: 'Constantine', nameAr: 'قسنطينة' },
  { id: 26, code: '26', name: 'Médéa', nameAr: 'المدية' },
  { id: 27, code: '27', name: 'Mostaganem', nameAr: 'مستغانم' },
  { id: 28, code: '28', name: "M'Sila", nameAr: 'المسيلة' },
  { id: 29, code: '29', name: 'Mascara', nameAr: 'معسكر' },
  { id: 30, code: '30', name: 'Ouargla', nameAr: 'ورقلة' },
  { id: 31, code: '31', name: 'Oran', nameAr: 'وهران' },
  { id: 32, code: '32', name: 'El Bayadh', nameAr: 'البيض' },
  { id: 33, code: '33', name: 'Illizi', nameAr: 'إليزي' },
  { id: 34, code: '34', name: 'Bordj Bou Arréridj', nameAr: 'برج بوعريريج' },
  { id: 35, code: '35', name: 'Boumerdès', nameAr: 'بومرداس' },
  { id: 36, code: '36', name: 'El Tarf', nameAr: 'الطارف' },
  { id: 37, code: '37', name: 'Tindouf', nameAr: 'تندوف' },
  { id: 38, code: '38', name: 'Tissemsilt', nameAr: 'تيسمسيلت' },
  { id: 39, code: '39', name: 'El Oued', nameAr: 'الوادي' },
  { id: 40, code: '40', name: 'Khenchela', nameAr: 'خنشلة' },
  { id: 41, code: '41', name: 'Souk Ahras', nameAr: 'سوق أهراس' },
  { id: 42, code: '42', name: 'Tipaza', nameAr: 'تيبازة' },
  { id: 43, code: '43', name: 'Mila', nameAr: 'ميلة' },
  { id: 44, code: '44', name: 'Aïn Defla', nameAr: 'عين الدفلى' },
  { id: 45, code: '45', name: 'Naâma', nameAr: 'النعامة' },
  { id: 46, code: '46', name: 'Aïn Témouchent', nameAr: 'عين تموشنت' },
  { id: 47, code: '47', name: 'Ghardaïa', nameAr: 'غرداية' },
  { id: 48, code: '48', name: 'Relizane', nameAr: 'غليزان' },
  { id: 49, code: '49', name: 'Timimoun', nameAr: 'تيميمون' },
  { id: 50, code: '50', name: 'Bordj Badji Mokhtar', nameAr: 'برج باجي مختار' },
  { id: 51, code: '51', name: 'Ouled Djellal', nameAr: 'أولاد جلال' },
  { id: 52, code: '52', name: 'Béni Abbès', nameAr: 'بني عباس' },
  { id: 53, code: '53', name: 'In Salah', nameAr: 'عين صالح' },
  { id: 54, code: '54', name: 'In Guezzam', nameAr: 'عين قزام' },
  { id: 55, code: '55', name: 'Touggourt', nameAr: 'تقرت' },
  { id: 56, code: '56', name: 'Djanet', nameAr: 'جانت' },
  { id: 57, code: '57', name: "El M'Ghair", nameAr: 'المغير' },
  { id: 58, code: '58', name: 'El Menia', nameAr: 'المنيعة' },
];
